cache: bundler

sudo: required

language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4

script: bundle exec rspec

before_script:
  - sudo cp /usr/share/doc/mysql-server-5.6/examples/my-default.cnf /usr/share/mysql/my-default.cnf

